/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seovan.es.dialogs;

import beleris.es.finaldbmanager.FDBMan;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import seovan.es.programconfig.PConfigManager;
import static seovan.es.programconfig.PConfigManager.PConfig;

/**
 *
 * @author edavid
 */
public class SearchingDlg extends javax.swing.JDialog {

    private static final long serialVersionUID = -5128974329527233716L;

    CLAllObjectList<Integer> ListofsearchedItems = new CLAllObjectList<>();

    /**
     * @return the encontrado
     */
    public boolean isEncontrado() {
        return encontrado;
    }

    /**
     * @param encontrado the encontrado to set
     */
    public void setEncontrado(boolean encontrado) {
        this.encontrado = encontrado;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchingDlg.class.getName());
    private FDBMan DBMSAP;
    private int searcheditem = 0;
    private boolean encontrado = false;

    /**
     *
     * @param parent
     * @param modal
     */
    public SearchingDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form SearchingDlg
     *
     * @param parent
     * @param modal
     * @param tmpidxitem
     */
    public SearchingDlg(java.awt.Frame parent, boolean modal, int tmpidxitem) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JBGANDORINFO1 = new javax.swing.ButtonGroup();
        JBGANDORINFO2 = new javax.swing.ButtonGroup();
        JBGANDORINFO3 = new javax.swing.ButtonGroup();
        JBGANDORINFO4 = new javax.swing.ButtonGroup();
        JBGANDORINFO5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JSearchButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSearchTitleSubCNF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSearchUpdateDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSearchPublicDate = new javax.swing.JTextField();
        jSearchLanguage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSearchNumber = new javax.swing.JTextField();
        jRBAND1 = new javax.swing.JRadioButton();
        JRBOR1 = new javax.swing.JRadioButton();
        jRBAND2 = new javax.swing.JRadioButton();
        JRBOR2 = new javax.swing.JRadioButton();
        jRBAND3 = new javax.swing.JRadioButton();
        JRBOR3 = new javax.swing.JRadioButton();
        jRBAND4 = new javax.swing.JRadioButton();
        JRBOR4 = new javax.swing.JRadioButton();
        jRBAND5 = new javax.swing.JRadioButton();
        JRBOR5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.title")); // NOI18N
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1100, 710));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        setPreferredSize(new java.awt.Dimension(1100, 710));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 0, 14))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(JSearchButton, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JSearchButton.text")); // NOI18N
        JSearchButton.setMaximumSize(new java.awt.Dimension(300, 50));
        JSearchButton.setMinimumSize(new java.awt.Dimension(300, 50));
        JSearchButton.setPreferredSize(new java.awt.Dimension(300, 50));
        JSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSearchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(JSearchButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jButton1.text")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(300, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(300, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(300, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jButton1, gridBagConstraints);

        jPanel2.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jSearchTitleSubCNF.setText(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jSearchTitleSubCNF.text")); // NOI18N
        jSearchTitleSubCNF.setMaximumSize(new java.awt.Dimension(600, 30));
        jSearchTitleSubCNF.setMinimumSize(new java.awt.Dimension(600, 30));
        jSearchTitleSubCNF.setPreferredSize(new java.awt.Dimension(600, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jSearchTitleSubCNF, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        jSearchUpdateDate.setText(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jSearchUpdateDate.text")); // NOI18N
        jSearchUpdateDate.setMaximumSize(new java.awt.Dimension(600, 30));
        jSearchUpdateDate.setMinimumSize(new java.awt.Dimension(600, 30));
        jSearchUpdateDate.setPreferredSize(new java.awt.Dimension(600, 30));
        jSearchUpdateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchUpdateDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jSearchUpdateDate, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        jSearchPublicDate.setText(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jSearchPublicDate.text")); // NOI18N
        jSearchPublicDate.setMaximumSize(new java.awt.Dimension(600, 30));
        jSearchPublicDate.setMinimumSize(new java.awt.Dimension(600, 30));
        jSearchPublicDate.setPreferredSize(new java.awt.Dimension(600, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jSearchPublicDate, gridBagConstraints);

        jSearchLanguage.setText(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jSearchLanguage.text")); // NOI18N
        jSearchLanguage.setMaximumSize(new java.awt.Dimension(600, 30));
        jSearchLanguage.setMinimumSize(new java.awt.Dimension(600, 30));
        jSearchLanguage.setPreferredSize(new java.awt.Dimension(600, 30));
        jSearchLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchLanguageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jSearchLanguage, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jLabel4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jLabel5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        jSearchNumber.setText(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jSearchNumber.text")); // NOI18N
        jSearchNumber.setMaximumSize(new java.awt.Dimension(600, 30));
        jSearchNumber.setMinimumSize(new java.awt.Dimension(600, 30));
        jSearchNumber.setPreferredSize(new java.awt.Dimension(600, 30));
        jSearchNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jSearchNumber, gridBagConstraints);

        JBGANDORINFO1.add(jRBAND1);
        org.openide.awt.Mnemonics.setLocalizedText(jRBAND1, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jRBAND1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBAND1, gridBagConstraints);

        JBGANDORINFO1.add(JRBOR1);
        JRBOR1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(JRBOR1, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JRBOR1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(JRBOR1, gridBagConstraints);

        JBGANDORINFO2.add(jRBAND2);
        org.openide.awt.Mnemonics.setLocalizedText(jRBAND2, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jRBAND2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBAND2, gridBagConstraints);

        JBGANDORINFO2.add(JRBOR2);
        JRBOR2.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(JRBOR2, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JRBOR2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(JRBOR2, gridBagConstraints);

        JBGANDORINFO3.add(jRBAND3);
        org.openide.awt.Mnemonics.setLocalizedText(jRBAND3, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jRBAND3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBAND3, gridBagConstraints);

        JBGANDORINFO3.add(JRBOR3);
        JRBOR3.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(JRBOR3, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JRBOR3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(JRBOR3, gridBagConstraints);

        JBGANDORINFO4.add(jRBAND4);
        org.openide.awt.Mnemonics.setLocalizedText(jRBAND4, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jRBAND4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBAND4, gridBagConstraints);

        JBGANDORINFO4.add(JRBOR4);
        JRBOR4.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(JRBOR4, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JRBOR4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(JRBOR4, gridBagConstraints);

        JBGANDORINFO5.add(jRBAND5);
        org.openide.awt.Mnemonics.setLocalizedText(jRBAND5, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jRBAND5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBAND5, gridBagConstraints);

        JBGANDORINFO5.add(JRBOR5);
        JRBOR5.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(JRBOR5, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JRBOR5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        jPanel2.add(JRBOR5, gridBagConstraints);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int Searching(CLAllObjectList<CLAllObjectList<String>> LIST, String PSearchPhrase, int tmpIndexDataTotal) {
        int result = -1;
        for (int tmpitems = 1; tmpitems <= tmpIndexDataTotal; tmpitems++) {
            int irows = LIST.get(tmpitems).size();
            for (int si = 0; si < irows; si++) {
                String SearchPhrase = LIST.get(tmpitems).get(si);
                // String TSearchPhrase=jSearchTitleSubCNF.getText();
                if (SearchPhrase.contains(PSearchPhrase)) {
                    result = tmpitems;
                    setEncontrado(true);
                    break;
                }
            }
        }
        return result;
    }

    int GlobalSearch(int searcheditem, String Phrase) {
        CLAllObjectList<Integer> SavedListofsearchedItems = new CLAllObjectList<>();
        DBMSAP = new FDBMan("jdbc:mysql://localhost:3306/desidaniespsources", PConfig.getConfPassDB(), "desidaniespsources", PConfig.getConfUserDB(), PConfigManager.PConfig.getDatabaseManagerinUse());
        CLAllObjectList<String> ColumnsName = DBMSAP.GetColumnsName("elements_record");
        CLAllObjectList<CLAllObjectList<String>> Records_List = DBMSAP.LoadList_Table("desidaniespsources", "elements_record", ColumnsName);
        int IndexDataTotal = Records_List.get(0).size();
        DBMSAP = new FDBMan("jdbc:mysql://localhost:3306/sourcesevalprotocol", PConfig.getConfPassDB(), "sourcesevalprotocol", PConfig.getConfUserDB(), PConfigManager.PConfig.getDatabaseManagerinUse());
        CLAllObjectList<String> ListSourcelevel_ent = DBMSAP.LoadList("list_sourcelevel", "sourcelevelitem");
        CLAllObjectList<String> ListSourceOriginTable_ent = DBMSAP.LoadList("list_source_origin_table", "originitem");
        CLAllObjectList<String> ListGeoCoverTable_ent = DBMSAP.LoadList("list_geo_cover_table", "geographicvoveritem");
        CLAllObjectList<String> ListFormatMediumTable_ent = DBMSAP.LoadList("list_format_medium_table", "format_mediumitem");
        CLAllObjectList<String> ListSourcecontents_ent = DBMSAP.LoadList("list_sourcecontents", "sourcecontentsitem");
        CLAllObjectList<String> ListAccessTable_ent = DBMSAP.LoadList("list_access_table", "access_item"); // TODO add your handling code here:
        ColumnsName = DBMSAP.GetColumnsName("identification");
        CLAllObjectList<CLAllObjectList<String>> IDENT = DBMSAP.LoadList_Table("desidaniespsources", "identification", ColumnsName);
        searcheditem = Searching(IDENT, Phrase, IndexDataTotal);
        //IDENT.clear();
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("tipification");
            CLAllObjectList<CLAllObjectList<String>> TIP = DBMSAP.LoadList_Table("desidaniespsources", "tipification", ColumnsName);
            searcheditem = Searching(TIP, Phrase, IndexDataTotal);
            TIP.clear();
        }

        if (JRBOR1.isEnabled() && searcheditem != -1) {
            ListofsearchedItems.add(searcheditem);
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("authorities");
            CLAllObjectList<CLAllObjectList<String>> AUTHOR = DBMSAP.LoadList_Table("desidaniespsources", "authorities", ColumnsName);
            searcheditem = Searching(AUTHOR, Phrase, IndexDataTotal);
            AUTHOR.clear();
        }

        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("temclass");
            CLAllObjectList<CLAllObjectList<String>> TEMCLASS = DBMSAP.LoadList_Table("desidaniespsources", "temclass", ColumnsName);
            searcheditem = Searching(TEMCLASS, Phrase, IndexDataTotal);
            TEMCLASS.clear();
        }

        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("contents");
            CLAllObjectList<CLAllObjectList<String>> CONTENT = DBMSAP.LoadList_Table("desidaniespsources", "contents", ColumnsName);
            searcheditem = Searching(CONTENT, Phrase, IndexDataTotal);
            CONTENT.clear();
        }

        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("sourceapplication");
            CLAllObjectList<CLAllObjectList<String>> APLICUTIL = DBMSAP.LoadList_Table("desidaniespsources", "sourceapplication", ColumnsName);
            searcheditem = Searching(APLICUTIL, Phrase, IndexDataTotal);
            APLICUTIL.clear();
        }
        if (JRBOR1.isEnabled() && searcheditem != -1) {
            ListofsearchedItems.add(searcheditem);
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("evaluation");
            CLAllObjectList<CLAllObjectList<String>> EVAL = DBMSAP.LoadList_Table("desidaniespsources", "evaluation", ColumnsName);
            searcheditem = Searching(EVAL, Phrase, IndexDataTotal);
            EVAL.clear();
        }
        if (jRBAND1.isEnabled() && searcheditem != -1) {
            SavedListofsearchedItems.add(searcheditem);
        }
        if (JRBOR1.isEnabled() && searcheditem != -1) {
            ListofsearchedItems.add(searcheditem);
        }
        if (searcheditem == -1) {
            searcheditem = Searching(IDENT, jSearchUpdateDate.getText(), IndexDataTotal);

        }
        if (JRBOR2.isEnabled() && searcheditem != -1) {
            ListofsearchedItems.add(searcheditem);

        }
        if (searcheditem == -1) {
            searcheditem = Searching(IDENT, jSearchPublicDate.getText(), IndexDataTotal);

        }
        if (JRBOR3.isEnabled() && searcheditem != -1) {

            ListofsearchedItems.add(searcheditem);
        }
        if (searcheditem == -1) {
            searcheditem = Searching(IDENT, jSearchLanguage.getText(), IndexDataTotal);

        }
        if (JRBOR4.isEnabled() && searcheditem != -1) {

            ListofsearchedItems.add(searcheditem);
        }
        if (searcheditem == -1) {
            searcheditem = Searching(IDENT, jSearchNumber.getText(), IndexDataTotal);

        }
        if (JRBOR5.isEnabled() && searcheditem != -1) {

            ListofsearchedItems.add(searcheditem);
        }
        return searcheditem;
    }

    private void JSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSearchButtonActionPerformed
        int searcheditem = -1;
        //CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();
        searcheditem = GlobalSearch(searcheditem, jSearchTitleSubCNF.getText());
        ListofsearchedItems.add(searcheditem);
        dispose();
    }//GEN-LAST:event_JSearchButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSearchUpdateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchUpdateDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchUpdateDateActionPerformed

    private void jSearchLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchLanguageActionPerformed

    private void jSearchNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SearchingDlg dialog = new SearchingDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JBGANDORINFO1;
    private javax.swing.ButtonGroup JBGANDORINFO2;
    private javax.swing.ButtonGroup JBGANDORINFO3;
    private javax.swing.ButtonGroup JBGANDORINFO4;
    private javax.swing.ButtonGroup JBGANDORINFO5;
    private javax.swing.JRadioButton JRBOR1;
    private javax.swing.JRadioButton JRBOR2;
    private javax.swing.JRadioButton JRBOR3;
    private javax.swing.JRadioButton JRBOR4;
    private javax.swing.JRadioButton JRBOR5;
    private javax.swing.JButton JSearchButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBAND1;
    private javax.swing.JRadioButton jRBAND2;
    private javax.swing.JRadioButton jRBAND3;
    private javax.swing.JRadioButton jRBAND4;
    private javax.swing.JRadioButton jRBAND5;
    private javax.swing.JTextField jSearchLanguage;
    private javax.swing.JTextField jSearchNumber;
    private javax.swing.JTextField jSearchPublicDate;
    private javax.swing.JTextField jSearchTitleSubCNF;
    private javax.swing.JTextField jSearchUpdateDate;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the searcheditem
     */
    public int getSearcheditem() {
        return searcheditem;
    }

    /**
     * @param searcheditem the searcheditem to set
     */
    public void setSearcheditem(int searcheditem) {
        this.searcheditem = searcheditem;
    }
}
