/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seovan.es.dialogs;

import beleris.es.finaldbmanager.FDBMan;
import beleris.es.finalprimaryclasses.CLAllObjectList;
import seovan.es.programconfig.PConfigManager;
import static seovan.es.programconfig.PConfigManager.PConfig;

/**
 *
 * @author edavid
 */
public class SearchingDlg extends javax.swing.JDialog {

    private static final long serialVersionUID = -5128974329527233716L;


    /**
     * @return the encontrado
     */
    public boolean isEncontrado() {
        return encontrado;
    }

    /**
     * @param encontrado the encontrado to set
     */
    public void setEncontrado(boolean encontrado) {
        this.encontrado = encontrado;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchingDlg.class.getName());
    private FDBMan DBMSAP;
    private FDBMan DBMSEV;
    int idxitem = 0;
    private int searcheditem = 0;
    private boolean encontrado=false;

    /**
     *
     * @param parent
     * @param modal
     */
    public SearchingDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form SearchingDlg
     * @param parent
     * @param modal
     * @param tmpidxitem
     */
    public SearchingDlg(java.awt.Frame parent, boolean modal, int tmpidxitem) {
        super(parent, modal);
        initComponents();
        idxitem = tmpidxitem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSearchPhrase = new javax.swing.JTextField();
        JSearchButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.title")); // NOI18N
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 0, 14))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jSearchPhrase.setText(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jSearchPhrase.text")); // NOI18N
        jSearchPhrase.setMaximumSize(new java.awt.Dimension(600, 50));
        jSearchPhrase.setMinimumSize(new java.awt.Dimension(600, 50));
        jSearchPhrase.setPreferredSize(new java.awt.Dimension(600, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jSearchPhrase, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JSearchButton, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.JSearchButton.text")); // NOI18N
        JSearchButton.setMaximumSize(new java.awt.Dimension(300, 50));
        JSearchButton.setMinimumSize(new java.awt.Dimension(300, 50));
        JSearchButton.setPreferredSize(new java.awt.Dimension(300, 50));
        JSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSearchButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(JSearchButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.jButton1.text")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(300, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(300, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(300, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(SearchingDlg.class, "SearchingDlg.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int Searching(CLAllObjectList<CLAllObjectList<String>> LIST, int tmpIndexDataTotal) {
        int result = -1;
        for (int tmpitems = 1; tmpitems <= tmpIndexDataTotal; tmpitems++) {
            int irows = LIST.get(tmpitems).size();
            for (int si = 0; si < irows; si++) {
                String SearchPhrase = LIST.get(tmpitems).get(si);
                String TSearchPhrase=jSearchPhrase.getText();
                if (SearchPhrase.contains(TSearchPhrase)) {
                    result = tmpitems;
                    setEncontrado(true);
                    break;                 
                }
            }
        }
        return result;
    }


    private void JSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSearchButtonActionPerformed
        int searcheditem = -1;
        DBMSAP = new FDBMan("jdbc:mysql://localhost:3306/desidaniespsources", PConfig.getConfPassDB(), "desidaniespsources", PConfig.getConfUserDB(), PConfigManager.PConfig.getDatabaseManagerinUse());
        CLAllObjectList<String> ColumnsName = DBMSAP.GetColumnsName("elements_record");
        CLAllObjectList<CLAllObjectList<String>> Records_List = DBMSAP.LoadList_Table("desidaniespsources", "elements_record", ColumnsName);
        int IndexDataTotal = Records_List.get(0).size();
        DBMSEV = new FDBMan("jdbc:mysql://localhost:3306/sourcesevalprotocol", PConfig.getConfPassDB(), "sourcesevalprotocol", PConfig.getConfUserDB(), PConfigManager.PConfig.getDatabaseManagerinUse());
        CLAllObjectList<String> ListSourcelevel_ent = DBMSAP.LoadList("list_sourcelevel", "sourcelevelitem");
        CLAllObjectList<String> ListSourceOriginTable_ent = DBMSAP.LoadList("list_source_origin_table", "originitem");
        CLAllObjectList<String> ListGeoCoverTable_ent = DBMSAP.LoadList("list_geo_cover_table", "geographicvoveritem");
        CLAllObjectList<String> ListFormatMediumTable_ent = DBMSAP.LoadList("list_format_medium_table", "format_mediumitem");
        CLAllObjectList<String> ListSourcecontents_ent = DBMSAP.LoadList("list_sourcecontents", "sourcecontentsitem");
        CLAllObjectList<String> ListAccessTable_ent = DBMSAP.LoadList("list_access_table", "access_item"); // TODO add your handling code here:
        //CLAllObjectList<String> ColumnsName = new CLAllObjectList<>();
        ColumnsName = DBMSAP.GetColumnsName("identification");
        CLAllObjectList<CLAllObjectList<String>> IDENT = DBMSAP.LoadList_Table("desidaniespsources", "identification", ColumnsName);
        searcheditem = Searching(IDENT, IndexDataTotal);
        IDENT.clear();
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("tipification");
            CLAllObjectList<CLAllObjectList<String>> TIP = DBMSAP.LoadList_Table("desidaniespsources", "tipification", ColumnsName);
            searcheditem = Searching(TIP, IndexDataTotal);
            TIP.clear();
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("authorities");
            CLAllObjectList<CLAllObjectList<String>> AUTHOR = DBMSAP.LoadList_Table("desidaniespsources", "authorities", ColumnsName);
            searcheditem = Searching(AUTHOR, IndexDataTotal);
            AUTHOR.clear();
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("temclass");
            CLAllObjectList<CLAllObjectList<String>> TEMCLASS = DBMSAP.LoadList_Table("desidaniespsources", "temclass", ColumnsName);
            searcheditem = Searching(TEMCLASS, IndexDataTotal);
            TEMCLASS.clear();
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("contents");
            CLAllObjectList<CLAllObjectList<String>> CONTENT = DBMSAP.LoadList_Table("desidaniespsources", "contents", ColumnsName);
            searcheditem = Searching(CONTENT, IndexDataTotal);
            CONTENT.clear();
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("sourceapplication");
            CLAllObjectList<CLAllObjectList<String>> APLICUTIL = DBMSAP.LoadList_Table("desidaniespsources", "sourceapplication", ColumnsName);
            searcheditem = Searching(APLICUTIL, IndexDataTotal);
            APLICUTIL.clear();
        }
        if (searcheditem == -1) {
            ColumnsName = DBMSAP.GetColumnsName("evaluation");
            CLAllObjectList<CLAllObjectList<String>> EVAL = DBMSAP.LoadList_Table("desidaniespsources", "evaluation", ColumnsName);
            searcheditem = Searching(EVAL, IndexDataTotal);
            EVAL.clear();
        }
        setSearcheditem(searcheditem);
        dispose();
    }//GEN-LAST:event_JSearchButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SearchingDlg dialog = new SearchingDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JSearchButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jSearchPhrase;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the searcheditem
     */
    public int getSearcheditem() {
        return searcheditem;
    }

    /**
     * @param searcheditem the searcheditem to set
     */
    public void setSearcheditem(int searcheditem) {
        this.searcheditem = searcheditem;
    }
}
