/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package seovan.es.generalmods;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//seovan.es.generalmods//SearchWindlw//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SearchWindlwTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "seovan.es.generalmods.SearchWindlwTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SearchWindlwAction",
        preferredID = "SearchWindlwTopComponent"
)
@Messages({
    "CTL_SearchWindlwAction=SearchWindlw",
    "CTL_SearchWindlwTopComponent=SearchWindlw Window",
    "HINT_SearchWindlwTopComponent=This is a SearchWindlw window"
})
public final class SearchWindowTopComponent extends TopComponent {

    public SearchWindowTopComponent() {
        initComponents();
        setName(Bundle.CTL_SearchWindlwTopComponent());
        setToolTipText(Bundle.HINT_SearchWindlwTopComponent());
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jRightPanel = new javax.swing.JPanel();
        jLeftPanel = new javax.swing.JPanel();
        jLeftScrollPane = new javax.swing.JScrollPane();
        jLeftEditorPane = new javax.swing.JEditorPane();

        setToolTipText(org.openide.util.NbBundle.getMessage(SearchWindowTopComponent.class, "SearchWindowTopComponent.toolTipText")); // NOI18N
        setMaximumSize(new java.awt.Dimension(1618, 825));
        setMinimumSize(new java.awt.Dimension(1618, 825));
        setName("Ventana de Búsqueda"); // NOI18N

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1618, 825));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1618, 825));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1618, 825));

        jRightPanel.setMaximumSize(new java.awt.Dimension(1413, 825));
        jRightPanel.setMinimumSize(new java.awt.Dimension(1413, 825));

        javax.swing.GroupLayout jRightPanelLayout = new javax.swing.GroupLayout(jRightPanel);
        jRightPanel.setLayout(jRightPanelLayout);
        jRightPanelLayout.setHorizontalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1413, Short.MAX_VALUE)
        );
        jRightPanelLayout.setVerticalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jRightPanel);

        jLeftPanel.setMaximumSize(new java.awt.Dimension(100, 825));
        jLeftPanel.setMinimumSize(new java.awt.Dimension(100, 825));
        jLeftPanel.setPreferredSize(new java.awt.Dimension(100, 825));

        jLeftEditorPane.setText(org.openide.util.NbBundle.getMessage(SearchWindowTopComponent.class, "SearchWindowTopComponent.jLeftEditorPane.text")); // NOI18N
        jLeftEditorPane.setMaximumSize(new java.awt.Dimension(200, 825));
        jLeftEditorPane.setMinimumSize(new java.awt.Dimension(200, 825));
        jLeftEditorPane.setPreferredSize(new java.awt.Dimension(200, 825));
        jLeftScrollPane.setViewportView(jLeftEditorPane);

        javax.swing.GroupLayout jLeftPanelLayout = new javax.swing.GroupLayout(jLeftPanel);
        jLeftPanel.setLayout(jLeftPanelLayout);
        jLeftPanelLayout.setHorizontalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLeftScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jLeftPanelLayout.setVerticalGroup(
            jLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLeftScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jLeftPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jLeftEditorPane;
    private javax.swing.JPanel jLeftPanel;
    private javax.swing.JScrollPane jLeftScrollPane;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    /**
     * @return the jRightPanel
     */
    public javax.swing.JPanel getjRightPanel() {
        return jRightPanel;
    }

    /**
     * @param jRightPanel the jRightPanel to set
     */
    public void setjRightPanel(javax.swing.JPanel jRightPanel) {
        this.jRightPanel = jRightPanel;
    }
}
