/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package beleris.es.finalutils;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class DSelectXMLDlg extends javax.swing.JDialog {

    private static final long serialVersionUID = 4771290774016254002L;
    private static int xmlorpdf;
    private static final int ExportXML = 2;
    private static final int ExportPDF = 4;

    /**
     * Creates new form DSelectXMLDlg
     *
     * @param parent
     * @param modal
     */
    public DSelectXMLDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Configure_filters();
    }

    /**
     *
     */
    public void Configure_filters() {
        FileNameExtensionFilter filter;

        if (xmlorpdf == ExportXML) {
            filter = new FileNameExtensionFilter("Ficheros XML", "xml", "text");
        } else {
            filter = new FileNameExtensionFilter("Ficheros PDF", "pdf", "text");
        }
        SelectXMLFile.setFileFilter(filter);
    }

    /**
     *
     * @return
     */
    public JFileChooser GetFileChooser() {
        return SelectXMLFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectXMLFile = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(DSelectXMLDlg.class, "DSelectXMLDlg.title")); // NOI18N
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 600, 500));
        setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setModal(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        SelectXMLFile.setDialogTitle(org.openide.util.NbBundle.getMessage(DSelectXMLDlg.class, "DSelectXMLDlg.FileChooser.dialogTitle")); // NOI18N
        SelectXMLFile.setToolTipText(org.openide.util.NbBundle.getMessage(DSelectXMLDlg.class, "DSelectXMLDlg.FileChooser.toolTipText")); // NOI18N
        SelectXMLFile.setMaximumSize(new java.awt.Dimension(600, 500));
        SelectXMLFile.setMinimumSize(new java.awt.Dimension(600, 500));
        SelectXMLFile.setName("FileChooser"); // NOI18N
        SelectXMLFile.setPreferredSize(new java.awt.Dimension(600, 500));
        SelectXMLFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectXMLFileActionPerformed(evt);
            }
        });
        getContentPane().add(SelectXMLFile);
        SelectXMLFile.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(DSelectXMLDlg.class, "DSelectXMLDlg.FileChooser.AccessibleContext.accessibleName")); // NOI18N
        SelectXMLFile.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(DSelectXMLDlg.class, "DSelectXMLDlg.FileChooser.AccessibleContext.accessibleDescription")); // NOI18N

        getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(DSelectXMLDlg.class, "DSelectXMLDlg.AccessibleContext.accessibleDescription")); // NOI18N
        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectXMLFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectXMLFileActionPerformed
        dispose();
    }//GEN-LAST:event_SelectXMLFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
 /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSelectXMLDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSelectXMLDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSelectXMLDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSelectXMLDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {

            DSelectXMLDlg dialog = new DSelectXMLDlg(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser SelectXMLFile;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the xmlorpdf
     */
    public int getXmlorpdf() {
        return xmlorpdf;
    }

    /**
     * @param aXmlorpdf the xmlorpdf to set
     */
    public void setXmlorpdf(int aXmlorpdf) {
        xmlorpdf = aXmlorpdf;
    }

    /**
     * @return the ExportXML
     */
    public static int getExportXML() {
        return ExportXML;
    }

    /**
     * @return the ExportPDF
     */
    public static int getExportPDF() {
        return ExportPDF;
    }

}
