/*
 @author Emilio David Diaus López 2008-2025
 * *
 * *
 */
package beleris.es.finalinformationmanager;

/**
 *
 * @author Emilio David Diaus López 2008-2025
 */
public class Util_CustomErrorInfoPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -3057013893628885828L;

   

    /**
     * Creates new form CustomErrorInfoPanel
     */
    public Util_CustomErrorInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAErrorMessage = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);

        jScrollPane1.setBackground(java.awt.Color.lightGray);

        jTAErrorMessage.setBackground(java.awt.Color.lightGray);
        jTAErrorMessage.setColumns(20);
        jTAErrorMessage.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jTAErrorMessage.setLineWrap(true);
        jTAErrorMessage.setRows(5);
        jTAErrorMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTAErrorMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAErrorMessage;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTAErrorMessage
     */
    public javax.swing.JTextArea getjTAErrorMessage() {
        return jTAErrorMessage;
    }

    /**
     * @param jTAErrorMessage the jTAErrorMessage to set
     */
    public void setjTAErrorMessage(javax.swing.JTextArea jTAErrorMessage) {
        this.jTAErrorMessage = jTAErrorMessage;
    }
}
