/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package seovan.es.programconfig;

import beleris.es.finaldbmanager.FDBMan;
import java.awt.event.KeyEvent;
import static seovan.es.programconfig.PConfigManager.PConfig;

/**
 *
 * @author Emilio David Diaus López 2023-2025
 */
public class ProgramOptions extends javax.swing.JDialog {

    private static final long serialVersionUID = 1627L;

    /**
     * Creates new form ProgramOptions
     * @param parent
     * @param modal
     */
    public ProgramOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDatabasemanager(PConfig.getDatabaseManagerinUse());

        if (PConfig.getDatabaseManagerinUse() == PConfig.getDatabaseManagerinUse()) {
            jRBMySQLsel.setSelected(true);
            jRBSQLLiteSel.setSelected(false);
        } else {
            jRBSQLLiteSel.setSelected(true);
            jRBMySQLsel.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRBMySQLsel = new javax.swing.JRadioButton();
        jRBSQLLiteSel = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTFUserDB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFDBPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jBCancel = new javax.swing.JButton();
        JBAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.title")); // NOI18N
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 510, 700));
        setMinimumSize(new java.awt.Dimension(510, 700));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(250, 150));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 150));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRBMySQLsel);
        org.openide.awt.Mnemonics.setLocalizedText(jRBMySQLsel, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jRBMySQLsel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBMySQLsel, gridBagConstraints);

        buttonGroup1.add(jRBSQLLiteSel);
        org.openide.awt.Mnemonics.setLocalizedText(jRBSQLLiteSel, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jRBSQLLiteSel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jRBSQLLiteSel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jPanel2, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jPanel3.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jLabel3.text")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(275, 40));
        jLabel3.setMinimumSize(new java.awt.Dimension(275, 40));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(275, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel3, gridBagConstraints);

        JTFUserDB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFUserDB.setText(org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.JTFUserDB.text")); // NOI18N
        JTFUserDB.setMaximumSize(new java.awt.Dimension(275, 40));
        JTFUserDB.setMinimumSize(new java.awt.Dimension(275, 40));
        JTFUserDB.setPreferredSize(new java.awt.Dimension(275, 40));
        JTFUserDB.setSelectionEnd(0);
        JTFUserDB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AcciondeTeclas(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(JTFUserDB, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jLabel4.text")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(275, 40));
        jLabel4.setMinimumSize(new java.awt.Dimension(275, 40));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(275, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jLabel4, gridBagConstraints);

        JTFDBPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFDBPass.setText(org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.JTFDBPass.text")); // NOI18N
        JTFDBPass.setMaximumSize(new java.awt.Dimension(275, 40));
        JTFDBPass.setMinimumSize(new java.awt.Dimension(275, 40));
        JTFDBPass.setPreferredSize(new java.awt.Dimension(275, 40));
        JTFDBPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDBPassActionPerformed(evt);
            }
        });
        JTFDBPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(JTFDBPass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jPanel4, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel3, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBCancel, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.jBCancel.text")); // NOI18N
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jBCancel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(JBAccept, org.openide.util.NbBundle.getMessage(ProgramOptions.class, "ProgramOptions.JBAccept.text")); // NOI18N
        JBAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAcceptActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(JBAccept, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAcceptActionPerformed
        // TODO add your handling code here:
        if (jRBMySQLsel.isSelected() == true) {
            setDatabasemanager(FDBMan.DB_MYSQL_Selected);
        } else {
            setDatabasemanager(FDBMan.DB_SQLite_Selected);
        }
        if ((JTFUserDB.getText() == null ? PConfig.getConfUserDB() != null : !JTFUserDB.getText().equals(PConfig.getConfUserDB())) || (JTFDBPass.getPassword().toString() != PConfig.getConfPassDB())) {
            String dbUser = JTFUserDB.getText();
            PConfig.setConfUserDB(dbUser);
            String dbPass = JTFDBPass.getPassword().toString();
            PConfig.setConfPassDB(dbPass);
        }
        dispose();
    }//GEN-LAST:event_JBAcceptActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    private void JTFDBPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDBPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDBPassActionPerformed

    private void AcciondeTeclas(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AcciondeTeclas
        TeclasUser(evt);
    }//GEN-LAST:event_AcciondeTeclas

    private void PassPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassPressed
        // TODO add your handling code here:
        TeclasPasswd(evt);
    }//GEN-LAST:event_PassPressed

    void TeclasUser(java.awt.event.KeyEvent evt) {
        final int CV = KeyEvent.VK_V + KeyEvent.CTRL_DOWN_MASK;
        final int CC = KeyEvent.VK_C + KeyEvent.CTRL_DOWN_MASK;
        final int CX = KeyEvent.VK_X + KeyEvent.CTRL_DOWN_MASK;

        //  final int keyCV = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.CTRL_DOWN_MASK).getKeyCode();
        //  final int keyCC = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.CTRL_DOWN_MASK).getKeyCode();
        //   final int keyCX = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.CTRL_DOWN_MASK).getKeyCode();
        int tkc = evt.getKeyCode();

        switch (tkc) {
            case CV: {
                pasteuser();

            }
            case CC: {
                copyuser();

            }
            case CX: {
                cutuser();

            }

        }
    }

    void TeclasPasswd(java.awt.event.KeyEvent evt) {
        final int CV = KeyEvent.VK_V + KeyEvent.CTRL_DOWN_MASK;
        final int CC = KeyEvent.VK_C + KeyEvent.CTRL_DOWN_MASK;
        final int CX = KeyEvent.VK_X + KeyEvent.CTRL_DOWN_MASK;
        int tkc = evt.getKeyCode();
        switch (tkc) {
            case CV: {
                pastepass();
                break;
            }
            case CC: {
                copypass();
                break;
            }
            case CX: {
                cutpass();
                break;
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProgramOptions dialog = new ProgramOptions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAccept;
    private javax.swing.JPasswordField JTFDBPass;
    private javax.swing.JTextField JTFUserDB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBMySQLsel;
    private javax.swing.JRadioButton jRBSQLLiteSel;
    // End of variables declaration//GEN-END:variables
    private int databasemanager = 0;

    /**
     *
     */
    public void cutuser() {
        JTFUserDB.cut();
    }

    /**
     *
     */
    public void copyuser() {
        JTFUserDB.copy();
    }

    /**
     *
     */
    public void pasteuser() {
        JTFUserDB.paste();
    }

    /**
     *
     */
    public void cutpass() {
        JTFDBPass.cut();
    }

    /**
     *
     */
    public void copypass() {
        JTFDBPass.copy();
    }

    /**
     *
     */
    public void pastepass() {
        JTFDBPass.paste();
    }

    /**
     * @return the databasemanager
     */
    public int getDatabasemanager() {
        return databasemanager;
    }

    /**
     * @param databasemanager the databasemanager to set
     */
    public void setDatabasemanager(int databasemanager) {
        this.databasemanager = databasemanager;
    }
}
